baseURL: "https://panzerschokolade.klingt.org"
languageCode: "en-us"
defaultContentLanguage: "en"
title: "Panzerschokolade"
description: "Ewige Blumenkraft"

buildFuture: true
rssLimit: 1000
disableHugoGeneratorInject: true
disablePathToLower: true
enableRobotsTXT: true
newcontenteditor: "nvim"

imaging:
  quality: 90

taxonomies:
  tag: "tags"

outputs:
  home: ["HTML"]
  section: ["HTML"]
  page: ["HTML"]
# sitemap:
#   changeFreq: monthly

