name: "Panzerschokolade"

url: "https://panzerschokolade.klingt.org"
service_url: "https://panzerschokolade.klingt.org/service"

keywords:
  - "panzerkunst"

contact:
  web: "https://panzerschokolade.klingt.org"

social:
  mixcloud: "panzerschokolade"
