name: "Panzerschokolade"

url: "https://panzerschokolade.klingt.org"
service_url: "https://panzerschokolade.klingt.org/service"

keywords:
  - "panzerkunst"

contact:
  email: "schokolade@panzerkunst.wtf"
  web: "https://panzerschokolade.klingt.org"

social:
  twitter: "eichhorny"
  mixcloud: "panzerschokolade"

developer:
  name: "disktree"
  email: "admin@disktree.net"
  url: "https://disktree.net/"
