// Generated by Haxe 3.3.0
(function () { "use strict";
var panzerschokolade_App = function() { };
panzerschokolade_App.main = function() {
	window.onload = function() {
		window.console.log("|>4|\\|7_3|25(|-|0|(014|)3");
		window.addEventListener("contextmenu",function(e) {
			e.preventDefault();
		});
	};
};
panzerschokolade_App.main();
})();
