// Generated by Haxe 3.3.0
(function ($hx_exports) { "use strict";
$hx_exports["om"] = $hx_exports["om"] || {};
$hx_exports["om"]["api"] = $hx_exports["om"]["api"] || {};
$hx_exports["om"]["api"]["youtube"] = $hx_exports["om"]["api"]["youtube"] || {};
$hx_exports["om"]["api"]["youtube"]["YouTube"] = $hx_exports["om"]["api"]["youtube"]["YouTube"] || {};
var om_api_youtube_YouTube = function() { };
om_api_youtube_YouTube.__onReady = $hx_exports["om"]["api"]["youtube"]["YouTube"]["__onReady"] = function() {
	om_api_youtube_YouTube.callback();
};
om_api_youtube_YouTube.init = function(callback) {
	om_api_youtube_YouTube.callback = callback;
	var firstScriptElement = window.document.getElementsByTagName("script")[0];
	var scriptElement = window.document.createElement("script");
	scriptElement.src = "https://www.youtube.com/iframe_api";
	firstScriptElement.parentNode.insertBefore(scriptElement,firstScriptElement);
	var callbackElement = window.document.createElement("script");
	callbackElement.textContent = "function onYouTubeIframeAPIReady() { om.api.youtube.YouTube.__onReady(); }";
	firstScriptElement.parentNode.insertBefore(callbackElement,firstScriptElement);
};
var panzerschokolade_App = function() { };
panzerschokolade_App.main = function() {
	window.onload = function() {
		window.console.log("|>4|\\|7_3|25(|-|0|(014|)3");
		window.addEventListener("contextmenu",function(e) {
			e.preventDefault();
		});
		om_api_youtube_YouTube.init(function() {
			console.log("Youtube ready");
			panzerschokolade_App.video = new panzerschokolade_VideoPlayer(window.document.getElementById("youtube-player"));
			panzerschokolade_App.video.onEvent = function(e1) {
			};
			panzerschokolade_App.video.init(function() {
				console.log("Videoplayer ready");
			});
		});
	};
};
var panzerschokolade_VideoPlayer = function(element) {
	this.element = element;
};
panzerschokolade_VideoPlayer.prototype = {
	onEvent: function(e) {
	}
	,init: function(callback) {
		var _gthis = this;
		this.player = new YT.Player(this.element.id,{ width : "600", height : "400", playerVars : { controls : 0, color : "white", autoplay : 0, disablekb : 0, fs : 0, iv_load_policy : 3, modestbranding : 1, showinfo : 0}, events : { 'onReady' : function(e) {
			_gthis.player.loadVideoById("GI6dOS5ncFc");
		}, 'onStateChange' : $bind(this,this.handlePlayerStateChange), 'onPlaybackQualityChange' : $bind(this,this.handlePlaybackQualityChange), 'onPlaybackRateChange' : $bind(this,this.handlePlaybackRateChange), 'onError' : $bind(this,this.handlePlayerError)}});
	}
	,handlePlayerStateChange: function(e) {
		if(e == 5) {
			var pl = this.player.getPlaylist();
			console.log(pl.toString());
			var i = this.player.getPlaylistIndex();
			console.log(i);
		}
	}
	,handlePlaybackQualityChange: function(e) {
	}
	,handlePlaybackRateChange: function(e) {
	}
	,handlePlayerError: function(e) {
		console.log(e);
	}
};
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
panzerschokolade_App.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);

//# sourceMappingURL=panzerschokolade.js.map